on: pull_request
name: Test PR
jobs:
  unittests:
    name: Running the unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v3.2.5
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v2.1.5
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != true
        run: npm ci
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Execute the tests
        run: npm run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
