on: pull_request
name: Test PR
jobs:
  unittests:
    name: Running the unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v2.1.5
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != true
        run: npm ci
      - name: Execute the tests
        run: npm run test
  automate-pullrequest-review:
    runs-on: ubuntu-latest
    needs: unittests
    steps:
      - name: Approve pull request
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: APPROVE
          body: 'Thank you dependabot :+1:'
  automerge:
    runs-on: ubuntu-latest
    needs: [unittests, automate-pullrequest-review]
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "merge"
          MERGE_LABELS: "dependencies"
