name: On Published Release
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish to GitHub packages
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: npm cache
        id: new-cache
        uses: actions/cache@v3.0.10
        with:
          path: ~/.npm
          key: ${{ runner.os }}-new-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-new-cache-
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          always-auth: true
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != true
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run build
      - name: Publish to GitHub packages
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

